version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: my-sql-server
    environment:
      SA_PASSWORD: "StrongP@ssw0rd1"
      ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - backend-net

  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    container_name: my-webapi
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=SibersTest;User Id=sa;Password=StrongP@ssw0rd1;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-net

volumes:
  mssql-data:

networks:
  backend-net:
